export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

// export const USER_LOGINGH_REQUEST = 'USER_LOGINGH_REQUEST';
// export const USER_LOGINGH_SUCCESS = 'USER_LOGINGH_SUCCESS';
// export const USER_LOGINGH_FAIL = 'USER_LOGINGH_FAIL';
// export const USER_LOGOUTGH = 'USER_LOGOUTGH';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';