export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const VIDEO_CREATE_REQUEST = 'VIDEO_CREATE_REQUEST';
export const VIDEO_CREATE_SUCCESS = 'VIDEO_CREATE_SUCCESS';
export const VIDEO_CREATE_FAIL = 'VIDEO_CREATE_FAIL';
export const VIDEO_CREATE_RESET = 'VIDEO_CREATE_RESET';

export const VIDEO_LIST_REQUEST = 'VIDEO_LIST_REQUEST';
export const VIDEO_LIST_SUCCESS = 'VIDEO_LIST_SUCCESS';
export const VIDEO_LIST_FAIL = 'VIDEO_LIST_FAIL';

export const VIDEO_DETAILS_REQUEST = 'VIDEO_DETAILS_REQUEST';
export const VIDEO_DETAILS_SUCCESS = 'VIDEO_DETAILS_SUCCESS';
export const VIDEO_DETAILS_FAIL = 'VIDEO_DETAILS_FAIL';

export const VIDEO_DELETE_REQUEST = 'VIDEO_DELETE_REQUEST';
export const VIDEO_DELETE_SUCCESS = 'VIDEO_DELETE_SUCCESS';
export const VIDEO_DELETE_FAIL = 'VIDEO_DELETE_FAIL';

export const VIDEO_UPDATE_REQUEST = 'VIDEO_UPDATE_REQUEST';
export const VIDEO_UPDATE_SUCCESS = 'VIDEO_UPDATE_SUCCESS';
export const VIDEO_UPDATE_FAIL = 'VIDEO_UPDATE_FAIL';
export const VIDEO_UPDATE_RESET = 'VIDEO_UPDATE_RESET';

export const VIDEO_CREATE_REVIEW_REQUEST = 'VIDEO_CREATE_REVIEW_REQUEST';
export const VIDEO_CREATE_REVIEW_SUCCESS = 'VIDEO_CREATE_REVIEW_SUCCESS';
export const VIDEO_CREATE_REVIEW_FAIL = 'VIDEO_CREATE_REVIEW_FAIL';
export const VIDEO_CREATE_REVIEW_RESET = 'VIDEO_CREATE_REVIEW_RESET';

export const VIDEO_LIST_MY_REQUEST = 'VIDEO_LIST_MY_REQUEST';
export const VIDEO_LIST_MY_SUCCESS = 'VIDEO_LIST_MY_SUCCESS';
export const VIDEO_LIST_MY_FAIL = 'VIDEO_LIST_MY_FAIL';

export const COMMENT_CREATE_REQUEST = 'COMMENT_CREATE_REQUEST';
export const COMMENT_CREATE_SUCCESS = 'COMMENT_CREATE_SUCCESS';
export const COMMENT_CREATE_FAIL = 'COMMENT_CREATE_FAIL';


export const LIKE = 'LIKE';